### ISSUE TITLE
find_all error when used in function

### ISSUE THREAD

**Issue by jtexnl** [kelp404/bs4#1]
I'm trying to build a pretty simple scraper to harvest links as part of a crawler project. I've set up the following function to do the scraping:

    import requests as rq 
    from bs4 import BeautifulSoup

    def getHomepageLinks(page):
        homepageLinks = []
        response = rq.get(page)
        text = response.text
        soup = BeautifulSoup(text)
        for a in soup.find_all('a'):
            homepageLinks.append(a['href'])
        return homepageLinks'
I saved this file as "scraper2.py". When I try to run the code, I get the following error:

>>> import scraper2 as sc
>>> sc.getHomepageLinks('http://washingtonpost.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scraper2.py", line 9, in getHomepageLinks
    for a in soup.find_all('a'):
TypeError: 'NoneType' object is not callable

Now for the odd part: If I try to debug the code and just print the response, it works fine:

>>> response = rq.get('http://washingtonpost.com')
>>> text = response.text
>>> soup = BeautifulSoup(text)
>>> for a in soup.find_all('a'):
...     print(a['href'])
... 
https://www.washingtonpost.com
#
#
http://www.washingtonpost.com/politics/
https://www.washingtonpost.com/opinions/
http://www.washingtonpost.com/sports/
http://www.washingtonpost.com/local/
http://www.washingtonpost.com/national/
http://www.washingtonpost.com/world/
...

If I'm reading the error messages correctly, the problem is occurring with soup.find_all, but only when the find_all is part of a function. 

I've posted the question on StackOverflow, but nobody has an answer, so I thought this might be a bug. Has anyone else experienced this issue?

**Comment by laerus** [comment]
i cannot reproduce this
although not all 'a' tags will have the 'href' attribute
but the exception would have been a KeyError rather than TypeError
can you provide some more info?
